### ISSUE TITLE
Inquire about development direction

### ISSUE THREAD

**Issue by LiuZhu-CV** [yongsongH/Infrared_Image_SR_Survey#1]
Thanks for the excellent survey！Infrared image processing is rarely considered. In addition to super resolution, is there any other related information or review?

**Comment by yongsongH** [comment]
Hi, there 👋

Happy to know this work helps you!
I remember there was a survey, about the IR image dataset, that was mentioned in our paper.
According to my knowledge, this is the only IRSR system review.
Hope this helps you. 🤔

**Comment by LiuZhu-CV** [comment]
您好 您在做红外图像增强吗，还是只针对红外超分 我看相关工作都比较少

**Comment by yongsongH** [comment]
您好！感谢您对我们工作的关注。

我目前专注于IRSR的topic，关于其他IR image相关的工作，或许可以参考 [Prof. Cao Yanpeng](https://scholar.google.com/citations?user=4dWxYUkAAAAJ&hl=zh-CN) 组内的工作。希望这能对您有所帮助。

祝好！
